export ZSH_THEME="gister"
export GOPATH="$HOME/go/"
export ZSH_TMUX_AUTOSTART=true	
export ZSH_DISABLE_COMPFIX=true
export ZSH="/Users/i517616/.oh-my-zsh"
PATH=$PATH:$GOPATH/bin
PATH=$PATH/usr/local/opt/qt/bin
PATH=$PATH:/Users/i517616/go/bin
PATH=$PATH:/usr/local/opt/helm@2/bin
PATH=$PATH:/Users/i517616/Library/Python/3.7/bin

## ==== SET UP PLUGINS ====
source /usr/local/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle iterm2
antigen bundle history
antigen bundle colored-man-pages
antigen bundle kubectl
antigen bundle tmux

antigen bundle pPrecel/kyma-zsh
antigen bundle hlissner/zsh-autopair
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle vasyharan/zsh-brew-services

## ==== SET UP THEME ====
if ! test -f "$ZSH/custom/themes/natural-zsh-theme/natural.zsh-theme"
then
    git clone "https://github.com/pPrecel/natural-zsh-theme" \
        "$ZSH/custom/themes/natural-zsh-theme"
fi

antigen theme "$ZSH/custom/themes/natural-zsh-theme" \
    "natural.zsh-theme" --no-local-clone

antigen apply
## =========================

alias ls='lsd'
alias mockery="$GOPATH/bin/mockery"
alias pp="cd ${GOPATH}src/github.com/pPrecel"
alias kp="cd ${GOPATH}src/github.com/kyma-project"
alias ki="cd ${GOPATH}src/github.com/kyma-incubator"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/i517616/google-cloud-sdk/path.zsh.inc' ]
then . '/Users/i517616/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/i517616/google-cloud-sdk/completion.zsh.inc' ]
then . '/Users/i517616/google-cloud-sdk/completion.zsh.inc'; fi
