export GOPATH="$HOME/go/"
export ZSH_TMUX_AUTOSTART=true	
export ZSH_DISABLE_COMPFIX=true
PATH=$PATH:$GOPATH/bin
PATH=$PATH/usr/local/opt/qt/bin
PATH=$PATH:/Users/i517616/go/bin
PATH=$PATH:/usr/local/opt/helm@2/bin
PATH=$PATH:/Users/i517616/Library/Python/3.7/bin

# ## ==== SET UP PLUGINS ====
source <(antibody init)

antibody bundle robbyrussell/oh-my-zsh
antibody bundle "
    pPrecel/kyma-zsh
    hlissner/zsh-autopair
    zsh-users/zsh-autosuggestions
    vasyharan/zsh-brew-services

    robbyrussell/oh-my-zsh path:plugins/colored-man-pages
    robbyrussell/oh-my-zsh path:plugins/kubectl
    robbyrussell/oh-my-zsh path:plugins/git
    robbyrussell/oh-my-zsh path:plugins/iterm2
    robbyrussell/oh-my-zsh path:plugins/history
    robbyrussell/oh-my-zsh path:plugins/tmux
"

# Load theme from the bundle
antibody bundle "pPrecel/natural-zsh-theme"
source "$(antibody home)/https-COLON--SLASH--SLASH-github\
.com-SLASH-pPrecel-SLASH-natural-zsh-theme/natural.zsh-theme"
# ## =========================

alias ls='lsd'
alias mockery="$GOPATH/bin/mockery"
alias pp="cd ${GOPATH}src/github.com/pPrecel"
alias kp="cd ${GOPATH}src/github.com/kyma-project"
alias ki="cd ${GOPATH}src/github.com/kyma-incubator"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/i517616/google-cloud-sdk/path.zsh.inc' ]
then . '/Users/i517616/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/i517616/google-cloud-sdk/completion.zsh.inc' ]
then . '/Users/i517616/google-cloud-sdk/completion.zsh.inc'; fi
